[app]
    httpPort = 8080
    runMode = "debug"
    readTimeout = "10s"
    writeTimeout = "10s"

[log]
    dir = "/home/wang/log/go-web-demo/"
    stdout = true

[mysql]
    [mysql.school]
        addr = "127.0.0.1:3306"
        dsn = "root:12345678@tcp(127.0.0.1:3306)/school?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
        readDSN = ["root:12345678@tcp(127.0.0.1:3306)/school?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
        active = 5
        idle = 2
        idleTimeout = "4h"
        queryTimeout = "1s"
        execTimeout = "1s"
        tranTimeout = "2s"

[redis]
	addr = "127.0.0.1:6379"
	idle = 10
	active = 10
	dialTimeout = "1s"
	readTimeout = "500ms"
	writeTimeout = "1s"
	idleTimeout = "10s"

[httpClient]
    [httpClient.fantuan]
        addr = "http://fantuan.bz.mgtv.com"
        [httpClient.fantuan.clientConf]
            maxTotal = 10
            maxPerHost  = 10
            keepAlive = "5s"
            dialTimeout = "1s"
            timeout = "1s"
            [httpClient.fantuan.clientConf.breaker]
                namespace = "fantuan"
                timeout = "3s"
                maxConcurrentRequests = 5
                requestVolumeThreshold= 1
                sleepWindow = "5s"
                errorPercentThreshold = 50
